import { describe, expect, it } from "vitest";

import manifestExport from "@/manifest.config";

// defineManifest's return type is a union (object | promise | env-fn); the config
// here is the plain object form, so narrow to it once for the assertions below.
const manifest = manifestExport as chrome.runtime.ManifestV3;

// The manifest is generated by @crxjs/vite-plugin's defineManifest at build
// time; this locks the contract the rest of the extension is wired against —
// a silent rename here breaks content-script injection or the Mirror's CORS.
describe("manifest.config", () => {
  it("declares its MV3 permissions, Chrome floor, and Convex host", () => {
    expect(manifest.manifest_version).toBe(3);
    expect(manifest.description).toBe(
      "Save posts to your Lasso Folders from X, Threads, and Instagram — with keyboard-first shortcuts.",
    );
    expect(manifest.minimum_chrome_version).toBe("106");
    // ADR-0009: the sole host permission is the optional cross-origin Convex Mirror.
    expect(manifest.host_permissions).toEqual(["https://*.convex.cloud/*"]);
    expect(manifest.content_security_policy).toEqual({
      extension_pages:
        "script-src 'self'; object-src 'self'; connect-src https://*.convex.cloud wss://*.convex.cloud",
    });
  });

  it("injects the MAIN-world activator at document_start and the content script at idle", () => {
    const scripts = manifest.content_scripts ?? [];
    const mainWorld = scripts.find((s) => s.js?.includes("src/content/main-world.ts"));
    expect(mainWorld).toMatchObject({ run_at: "document_start", world: "MAIN" });
    expect(mainWorld?.matches).toEqual(["https://x.com/*"]);

    const content = scripts.find((s) => s.js?.includes("src/content/main.tsx"));
    expect(content).toMatchObject({ run_at: "document_idle", matches: ["https://x.com/*"] });
    const social = scripts.find((s) => s.js?.includes("src/content/non-x-main.tsx"));
    expect(social).toMatchObject({
      run_at: "document_idle",
      matches: [
        "https://threads.com/*",
        "https://www.threads.com/*",
        "https://threads.net/*",
        "https://www.threads.net/*",
        "https://instagram.com/*",
        "https://www.instagram.com/*",
      ],
    });
  });

  it("wires the service worker, popup, and options page", () => {
    expect(manifest.background).toMatchObject({
      service_worker: "src/background/index.ts",
      type: "module",
    });
    expect(manifest.action?.default_popup).toBe("src/popup/index.html");
    expect(manifest.options_ui).toMatchObject({
      page: "src/options/index.html",
      open_in_tab: true,
    });
  });
});
