import { describe, expect, it } from "vitest";

import manifestExport from "@/manifest.config";

// defineManifest's return type is a union (object | promise | env-fn); the config
// here is the plain object form, so narrow to it once for the assertions below.
const manifest = manifestExport as chrome.runtime.ManifestV3;

// The manifest is generated by @crxjs/vite-plugin's defineManifest at build
// time; this locks the contract the rest of the extension is wired against —
// a silent rename here breaks content-script injection or the Mirror's CORS.
describe("manifest.config", () => {
  it("declares an MV3 extension with the storage permission and the Convex host", () => {
    expect(manifest.manifest_version).toBe(3);
    expect(manifest.permissions).toEqual(["storage"]);
    // ADR-0009: the sole host permission is the optional cross-origin Convex Mirror.
    expect(manifest.host_permissions).toEqual(["https://*.convex.cloud/*"]);
  });

  it("injects the MAIN-world activator at document_start and the content script at idle", () => {
    const scripts = manifest.content_scripts ?? [];
    const mainWorld = scripts.find((s) => s.js?.includes("src/content/main-world.ts"));
    expect(mainWorld).toMatchObject({ run_at: "document_start", world: "MAIN" });
    expect(mainWorld?.matches).toEqual(["https://x.com/*", "https://twitter.com/*"]);

    const content = scripts.find((s) => s.js?.includes("src/content/main.tsx"));
    expect(content).toMatchObject({ run_at: "document_idle" });
  });

  it("wires the service worker, popup, and options page", () => {
    expect(manifest.background).toMatchObject({
      service_worker: "src/background/index.ts",
      type: "module",
    });
    expect(manifest.action?.default_popup).toBe("src/popup/index.html");
    expect(manifest.options_ui).toMatchObject({
      page: "src/options/index.html",
      open_in_tab: true,
    });
  });
});
